### ISSUE TITLE
Firefox - Small Buttons

### ISSUE THREAD

**Issue by douglascomim** [vinceliuice/Sierra-gtk-theme#1]
Hi,
very nice work and theme!
But had very small buttons on Firefox

![captura de tela de 2018-01-30 20-12-19](https://user-images.githubusercontent.com/29402875/35594479-7a0e71f8-05fa-11e8-91f0-78c1e15d1aed.png)

**Comment by vinceliuice** [comment]
In order to make it looks more like Mac OS, I set the button to be slim and long, but it seems that firefox's buttons get thinner and I'll try to find a solution!
