### ISSUE TITLE
not working well with xfce

### ISSUE THREAD

**Issue by kirk86** [vinceliuice/Sierra-gtk-theme#15]
Hi, thank you for this nice theme.
I've been trying to use it with xfce4 DE but it's not integrated very well. The top panel remains unchanged, as matter in fact it shows a very old panel style and. And the integration with dolphin doesn't work at all the colours for menus and folders are completely different.

**Comment by vinceliuice** [comment]
This theme has not been optimized for other desktops. I will fix such issues later.

**Comment by re23071998** [comment]
yeah, it also doesnt work with gtk 3.18

**Comment by possessedbysatan** [comment]
I second @kirk86. Doesn't work properly with XFCE. In my case, buttons have no borders and there are no close/minimize/maximize buttons for GTK3 apps, which render the theme unusable. 
Anyway, thanks for the theme. I hope it gets more recognition.
