### ISSUE TITLE
Missing restore-button

### ISSUE THREAD

**Issue by paullinuxthemer** [vinceliuice/Sierra-gtk-theme#2]
When using Chrome-browsers own (small) theme and maximize, the restore-button is missing.  You should make a button just like the maximize-button, but name it f.e. 

headerbar button.titlebutton.restore,
.titlebar button.titlebutton.restore{

color: transparent;
  background-color: transparent;
  background-position: center;
  background-repeat: no-repeat;
  border-width: 0; }

headerbar button.titlebutton.restore:backdrop,
.titlebar button.titlebutton.restore:backdrop{

 opacity: 0.8; }

headerbar button.titlebutton.restore,
.titlebar button.titlebutton.restore {

background-image: -gtk-scaled(url("objects/title-buttons/titlebutton-maximize.svg"), url("objects/title-buttons/titlebutton-maximize@2.svg")); }

headerbar button.titlebutton.restore:backdrop,
.titlebar button.titlebutton.restore:backdrop {

  background-image: -gtk-scaled(url("objects/title-buttons/titlebutton-maximize-backdrop.svg"), url("objects/title-buttons/titlebutton-maximize-backdrop@2.svg")); }

headerbar button.titlebutton.restore:hover,
.titlebar button.titlebutton.restore:hover {

  background-image: -gtk-scaled(url("objects/title-buttons/titlebutton-maximize-hover.svg"), url("objects/title-buttons/titlebutton-maximize-hover@2.svg")); }

headerbar button.titlebutton.restore:active,
.titlebar button.titlebutton.restore:active {

  background-image: -gtk-scaled(url("objects/title-buttons/titlebutton-maximize-active.svg"), url("objects/title-buttons/titlebutton-maximize-active@2.svg")); }

this is the CSS-part;

[CSS.txt](https://github.com/vinceliuice/Sierra-gtk-theme/files/1679996/CSS.txt)

**Comment by vinceliuice** [comment]
In fact these "restore" related code is currently superfluous, in order to repair the Chrome restore button bug before I was added these codes, but now Chrome no longer have this problem, so these codes also failed, nnd gtk window seems can not be use "background-image" to add a custom icon to restore button (but it can use the icon theme's restore icon file by default), so "restore" codes is also invalid for gtk3 softwares.
