### ISSUE TITLE
Please fix the bugs about alpha in _applications.scss

### ISSUE THREAD

**Issue by wangxa** [vinceliuice/Sierra-gtk-theme#23]
From line 1678, the alpha definitions look like `alpha (#000, 0.3)`. But in the generate CSS files, it is `alpha #000, 0.3`. So if you run gtk3-widget-factory from a terminal, you will see the error message. Since the function `gtkalpha` has been defined in `_common.scss`, these error alpha codes should be replaced using gtkalpha. And by the way, it is good if removing the whitespace between the function name and '(' for CSS.

**Comment by vinceliuice** [comment]
thanks for your reminder, I'll fix this soon
