### ISSUE TITLE
Gradient Top Bar

### ISSUE THREAD

**Issue by lightify97** [vinceliuice/Sierra-gtk-theme#25]
This theme is awesome. I've been looking for something like this for a long time. After installing I just found out that the top bar doesn't look exactly like macOS's. 
Just like this:
![s0010_menubar](https://user-images.githubusercontent.com/16276964/46190358-b7793d00-c30c-11e8-8a0e-23d33565cf76.png)
But it actually looks like this:
![topbar](https://user-images.githubusercontent.com/16276964/46190428-f0b1ad00-c30c-11e8-85f5-8ec5f9496548.png)
Not so cool!
Can you tell me the exact classes or elements that style the topbar?
REGARDS

**Comment by vinceliuice** [comment]
Gnome-shell is not mac top bar, we can't do it the same for now. and Blurring appmenu are not supported on gnome-shell

**Comment by lightify97** [comment]
I'm using Ubuntu Unity. The app menu is supported on Unity. Can you point out classes and elements that style the top bar or window title in maximized state?

**Comment by vinceliuice** [comment]
/src/gtk-3.0/sass/_unity.scss  You can edit this file to change unity style

**Comment by lightify97** [comment]
Let me check.

**Comment by lightify97** [comment]
![new](https://user-images.githubusercontent.com/16276964/46202868-62035700-c331-11e8-9498-3c73c4e7eca5.png)
This is what I was talking about. Though the gradient still doesn't work.
