### ISSUE TITLE
Bugs on xfce4-panel

### ISSUE THREAD

**Issue by sptndc** [vinceliuice/Sierra-gtk-theme#28]
Hello,
On my xfce4-panel maybe font color is wrong like this:

![screenshot_2018-11-07_22-52-29](https://user-images.githubusercontent.com/20803810/48145908-78b0ac80-e2e6-11e8-9079-1f01ba573715.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by sptndc** [comment]
Thanks @vinceliuice :+1:
