### ISSUE TITLE
Titlebar and main window color difference

### ISSUE THREAD

**Issue by dimitrov-adrian** [vinceliuice/Sierra-gtk-theme#3]
In Viber, Skype and PHPStorm I notice a color difference.

![screenshot from 2018-02-19 13-08-51](https://user-images.githubusercontent.com/1009639/36375047-56d0707a-1576-11e8-945c-fd6a79186cd3.png)

**Comment by vinceliuice** [comment]
Gtk3 software and Gtk2 software are different, Gtk2 theme can not set backdrop colors

**Comment by dimitrov-adrian** [comment]
Then is it possible to changing the titlebar color to match the window color?
