### ISSUE TITLE
switches widget with 1/0 symbol after gtk+ 3.24.5 update

### ISSUE THREAD

**Issue by dasnoopy** [vinceliuice/Sierra-gtk-theme#35]
Hi, after a recent update on my archlinux 64bit machine of gtk3 libs (ver 3.24.5)  switches widget in header bar appear with a weird 1/0  symbol  (see attacched  screenshot of gnome-tweaks)

as workaround I downgraded to gtk3+ 3.24.4  and switches are fine..

Thanks in advance for any help..
Andrea

![issue](https://user-images.githubusercontent.com/296922/52523461-07401b80-2c92-11e9-9982-10423a20b215.png)

**Comment by vinceliuice** [comment]
I updated the style for switches
