### ISSUE TITLE
Dashed Line

### ISSUE THREAD

**Issue by jmucero97** [vinceliuice/Sierra-gtk-theme#36]
Hello, first of all, I'm using latest Sierra-light-solid and latest ElementaryOS, that being said, I've noticed that in some applications, [when I scroll down a dashed line appears just below the top window bar.](https://imgur.com/a/uybspcg). It also happens in the terminal and in third-party applications like CoreBird.

**Comment by vinceliuice** [comment]
This is not a bug, this is the overflow line, only appear when the scrolled window overflows, if we don't have   this, we can not know the window is overflowed

**Comment by jmucero97** [comment]
Oh, thanks for the fast answer! Do you know if there is any way I could remove it? For me (personal opinion) it looks unaesthetic and out of place.

**Comment by vinceliuice** [comment]
You want remove all overflow lines or only the one of  ElementaryOS-setting window?

**Comment by jmucero97** [comment]
All the overflow lines

**Comment by vinceliuice** [comment]
then you can open ../gtk3.0/gtk.css and delete line 4104 to line 4186 ( all scrolledwindow overshoot * {...} and scrolledwindow undershoot * {...} ) then save it and reset the theme or relogin.
![2019-02-14 17-12-37](https://user-images.githubusercontent.com/7604295/52776345-587a5180-307c-11e9-9be1-aa1a1beed75d.png)

**Comment by jmucero97** [comment]
Thank you so much! It's worked!

**Comment by vinceliuice** [comment]
You are welcome!
