### ISSUE TITLE
[Request] Cinnamon Support

### ISSUE THREAD

**Issue by jmauss** [vinceliuice/Sierra-gtk-theme#39]
This theme seems to partially work with Cinnamon, but I was wondering if full compatibility could be made?

Thanks

**Comment by vinceliuice** [comment]
You can try this theme: https://github.com/vinceliuice/Mojave-gtk-theme
Mojave gtk theme supported Cinnamon shell theme, and I Sierra will support at future updates

**Comment by vinceliuice** [comment]
Now it's ok
