### ISSUE TITLE
Light Version not compatible with Gnome 3.34

### ISSUE THREAD

**Issue by QSCTech-Sange** [vinceliuice/Sierra-gtk-theme#44]
In the shell part, all the words become light green and cannot be seen clearly since the background is white. The Dark Version works fine.

**Comment by jimersylee** [comment]
some problem
[pic](https://i.loli.net/2019/10/29/pF4R85ZdvisGLqW.png)


 ██████████████████  ████████     jimersylee@laptop
 ██████████████████  ████████     OS: Manjaro 18.1.2 Juhraya
 ██████████████████  ████████     Kernel: x86_64 Linux 4.19.80-1-MANJARO
 ██████████████████  ████████     Uptime: 24m
 ████████            ████████     Packages: 1526
 ████████  ████████  ████████     Shell: zsh 5.7.1
 ████████  ████████  ████████     Resolution: 3840x1818
 ████████  ████████  ████████     DE: GNOME 3.34.1
 ████████  ████████  ████████     WM: Mutter
 ████████  ████████  ████████     WM Theme: Sierra-light
 ████████  ████████  ████████     GTK Theme: Sierra-compact-light [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Papirus-Dark-Maia
 ████████  ████████  ████████     Font: Noto Sans 11
 ████████  ████████  ████████     Disk: 91G / 110G (87%)
                                  CPU: Intel Core i7-8550U @ 8x 4GHz [44.0°C]
                                  GPU: Intel Corporation UHD Graphics 620 (rev 07)
                                  RAM: 4863MiB / 15923MiB

**Comment by vinceliuice** [comment]
Did you installed the last version from github?

**Comment by QSCTech-Sange** [comment]
The latest version solved the problem.

**Comment by jimersylee** [comment]
solved
