### ISSUE TITLE
http://ppa.launchpad.net/dyatlov-igor/sierra-theme/ubuntu eoan Release   404  Not Found [IP: 91.189.95.83 80]

### ISSUE THREAD

**Issue by lionkon1** [vinceliuice/Sierra-gtk-theme#46]
![image](https://user-images.githubusercontent.com/13028615/70403501-f73fc680-1a71-11ea-9d8d-baae1bb520a8.png)

**Comment by vinceliuice** [comment]
不要用这个ppa安装，直接github里下载用脚本安装，这个ppa不是我上传的，所以现在没人管了

**Comment by lionkon1** [comment]
ok,安装完了，怎么使用呀

**Comment by vinceliuice** [comment]
用gnome-tweaks设置主题就行了

**Comment by lionkon1** [comment]
嗯，对着做了，但是设置后好像不是全局的，只有部分主题被替换了。比如应用中心就不是透明的。谢谢，还是用原生的把先

**Comment by vinceliuice** [comment]
那是因为Ubuntu好多自带软件用的snap版本，不是源里的版本，snap版的应用不使用全局主题

**Comment by inkss** [comment]
可以把说明文档里的 PPA 相关去掉的
