### ISSUE TITLE
The google chrome problem about the native title bar

### ISSUE THREAD

**Issue by wangxa** [vinceliuice/Sierra-gtk-theme#5]
After installing Google chrome verson 65.0.3325.146. The GTK3 theme looks has problem for the minimisation, maximisation, and close buttons in the title bar if not using GTK title bar.

![screenshot from 2018-03-11 09-27-19](https://user-images.githubusercontent.com/1250269/37251820-008fc1c2-250f-11e8-8319-d9fc2b5ca66f.png)

**Comment by vinceliuice** [comment]
I got this problem too, I'm trying to fix now!

**Comment by vinceliuice** [comment]
Now fixed
